name: stacker_game
description: A simple Stacker game.
publish_to: 'none'
version: 1.0.8+9

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: 1.7.3
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  games_services: ^4.0.0
  intl: ^0.18.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/clock.png
    - assets/images/star_border.png
    - assets/images/star_filled.png